### ISSUE TITLE
prophunt gamemode/demo map steam links no longer work, any chance you have a backup?

### ISSUE THREAD

**Issue by successtheman** [Jackzmc/sourcemod-plugins#3]
Is there any chance you might have a backup of the prophunt gamemode/demo map files you could upload somewhere or add to the repo? 

I tried to click the steam links for the prophunt [gamemode](https://steamcommunity.com/sharedfiles/filedetails/?id=2850550331) and [demo map](https://steamcommunity.com/sharedfiles/filedetails/?id=2855027013) from the [readme](https://github.com/Jackzmc/sourcemod-plugins#l4d2_prophunt) but the links no longer work as shown in this screenshot
 
![firefox_jOB4R2TQ2Y](https://github.com/user-attachments/assets/ce9514e1-b393-4759-9ab1-48eb26ef3a2c)

**Comment by Jackzmc** [comment]
I made them friends only as I only worked on the gamemode once and I wasn't happy with the level of polish (of the plugin mostly), and I didn't think anyone was interested 

I made them public again, just warning it's very buggy to get started and might not work, I don't even remember anything about it.

**Comment by successtheman** [comment]
> I made them friends only as I only worked on the gamemode once and I wasn't happy with the level of polish (of the plugin mostly), and I didn't think anyone was interested
> 
> I made them public again, just warning it's very buggy to get started and might not work, I don't even remember anything about it.

thanks I wanted to check it out sounds fun
